name: default

channels:
  - conda-forge
  - nodefaults

dependencies:
  - black
  - jsonschema-with-format-nongpl
  - jupyter-packaging >=0.12
  - jupyterlab >=3.3,<4
  - nodejs >=18,<19
  - pip
  - python
  - python-build
  - ruff
  - twine
