#!/usr/bin/env bash
set -eux

jlpm --prefer-offline --ignore-optional

jlpm build

SKIP_POST_INSTALL=1 python -m pip install -e . --ignore-installed --no-deps

jupyter labextension develop . --overwrite

jupyter labextension list
