name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: mamba install python=${{ matrix.python-version }} pip nodejs jupyterlab=3 jupyter-packaging

    - name: Install jupyterlab_robotmode
      shell: bash -l {0}
      run: pip install -e .

    - name: Check installation files
      shell: bash -l {0}
      run: |
        test -d $CONDA_PREFIX/share/jupyter/labextensions/@marketsquare/jupyterlab_robotmode
        test -f $CONDA_PREFIX/share/jupyter/labextensions/@marketsquare/jupyterlab_robotmode/package.json

    - name: Check labextension
      shell: bash -l {0}
      run: |
        jupyter labextension list 2>&1 | grep -ie "@marketsquare/jupyterlab_robotmode.*enabled.*ok" -
