name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

env:
  CACHE_EPOCH: 0
  BINDER_ENV: .binder/environment.yml

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v1
      with:
        path: ~/conda_pkgs_dir
        key: |
          ${{ env.CACHE_EPOCH }}-${{ runner.os }}-conda-${{ hashFiles(env.BINDER_ENV) }}
        restore-keys:
          ${{ env.CACHE_EPOCH }}-${{ runner.os }}-conda-

    - name: Cache JS
      uses: actions/cache@v2
      with:
        path: node_modules
        key: |
          ${{ env.CACHE_EPOCH }}-node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@master  # TODO: revert to @v2 when miniforge available
      with:
        environment-file: ${{ env.BINDER_ENV }}
        miniconda-variant: Mambaforge
        use-only-tar-bz2: true

    - name: Install jupyterlab_robotmode
      run: python -m pip install -e . --no-build-isolation --no-deps

    - name: Run frontend unit tests
      run: jlpm test

    - name: Check installation files
      run: |
        test -d $CONDA_PREFIX/share/jupyter/labextensions/@marketsquare/jupyterlab_robotmode
        test -f $CONDA_PREFIX/share/jupyter/labextensions/@marketsquare/jupyterlab_robotmode/package.json

    - name: Check labextension
      run: |
        jupyter labextension list 2>&1 | grep -ie "@marketsquare/jupyterlab_robotmode.*enabled.*ok" -
